[package]
name = "libre_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk-decl = { version = "0.2.4", features = ["json"] }
fltk = "1.3.32"
