name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
    
    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev
         fi
      shell: bash
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      shell: bash
      run: git submodule update --init --recursive && cargo build --examples --verbose --features=use-ninja
